/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FP300Service */

#ifndef _Included_FP300Service
#define _Included_FP300Service
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FP300Service
 * Method:    SerialConnect
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_FP300Service_SerialConnect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     FP300Service
 * Method:    TCPConnect
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_FP300Service_TCPConnect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     FP300Service
 * Method:    GetTimeout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_FP300Service_GetTimeout
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    SetFPUTimeout
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_FP300Service_SetFPUTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SetDepartment
 * Signature: (ILjava/lang/String;IDI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetDepartment
  (JNIEnv *, jobject, jint, jstring, jint, jdouble, jint);

/*
 * Class:     FP300Service
 * Method:    GetDepartment
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetDepartment
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SetCreditInfo
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetCreditInfo
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     FP300Service
 * Method:    GetCreditInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetCreditInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SetCurrencyInfo
 * Signature: (ILjava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetCurrencyInfo
  (JNIEnv *, jobject, jint, jstring, jdouble);

/*
 * Class:     FP300Service
 * Method:    GetCurrencyInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetCurrencyInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SetMainCategory
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetMainCategory
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     FP300Service
 * Method:    GetMainCategory
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetMainCategory
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SetSubCategory
 * Signature: (ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetSubCategory
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     FP300Service
 * Method:    GetSubCategory
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetSubCategory
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SaveCashier
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SaveCashier
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     FP300Service
 * Method:    GetCashier
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetCashier
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SignInCashier
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SignInCashier
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     FP300Service
 * Method:    CheckCashierIsValid
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_CheckCashierIsValid
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     FP300Service
 * Method:    GetLogo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetLogo
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SetLogo
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetLogo
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     FP300Service
 * Method:    GetDateTime
 * Signature: ()LDateTime;
 */
JNIEXPORT jobject JNICALL Java_FP300Service_GetDateTime
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    SetDateTime
 * Signature: (LDateTime;LDateTime;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetDateTime
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     FP300Service
 * Method:    GetVATRate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetVATRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SetVATRate
 * Signature: (ID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetVATRate
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     FP300Service
 * Method:    SaveProduct
 * Signature: (ILjava/lang/String;IDILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SaveProduct
  (JNIEnv *, jobject, jint, jstring, jint, jdouble, jint, jstring, jint);

/*
 * Class:     FP300Service
 * Method:    GetProduct
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetProduct
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SaveGMPConnectionInfo
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SaveGMPConnectionInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     FP300Service
 * Method:    GetProgramOptions
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetProgramOptions
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    SaveProgramOptions
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SaveProgramOptions
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     FP300Service
 * Method:    PrintDocumentHeader
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintDocumentHeader__
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    PrintDocumentHeader
 * Signature: (Ljava/lang/String;DI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintDocumentHeader__Ljava_lang_String_2DI
  (JNIEnv *, jobject, jstring, jdouble, jint);

/*
 * Class:     FP300Service
 * Method:    PrintParkDocument
 * Signature: (Ljava/lang/String;LDateTime;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintParkDocument
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     FP300Service
 * Method:    PrintItem
 * Signature: (IDDLjava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintItem
  (JNIEnv *, jobject, jint, jdouble, jdouble, jstring, jint, jint);

/*
 * Class:     FP300Service
 * Method:    PrintAdjustment
 * Signature: (IDI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintAdjustment
  (JNIEnv *, jobject, jint, jdouble, jint);

/*
 * Class:     FP300Service
 * Method:    Correct
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_Correct
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    Void
 * Signature: (ID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_Void
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     FP300Service
 * Method:    PrintSubtotal
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintSubtotal
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     FP300Service
 * Method:    PrintPayment
 * Signature: (IID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintPayment
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     FP300Service
 * Method:    CloseReceipt
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_CloseReceipt
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     FP300Service
 * Method:    VoidReceipt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_VoidReceipt
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    PrintRemarkLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintRemarkLine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FP300Service
 * Method:    PrintReceiptBarcode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintReceiptBarcode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FP300Service
 * Method:    PrintXReport
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintXReport
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    PrintXPluReport
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintXPluReport
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     FP300Service
 * Method:    PrintZReport
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintZReport
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    PrintPeriodicZZReport
 * Signature: (IIIZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintPeriodicZZReport
  (JNIEnv *, jobject, jint, jint, jint, jboolean);

/*
 * Class:     FP300Service
 * Method:    PrintPeriodicDateReport
 * Signature: (LDateTime;LDateTime;IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintPeriodicDateReport
  (JNIEnv *, jobject, jobject, jobject, jint, jboolean);

/*
 * Class:     FP300Service
 * Method:    PrintEJPeriodic
 * Signature: (LDateTime;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintEJPeriodic__LDateTime_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    PrintEJPeriodic
 * Signature: (LDateTime;LDateTime;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintEJPeriodic__LDateTime_2LDateTime_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    PrintEJPeriodic
 * Signature: (IIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintEJPeriodic__IIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     FP300Service
 * Method:    PrintEJDetail
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintEJDetail
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    EnterServiceMode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_EnterServiceMode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FP300Service
 * Method:    ExitServiceMode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_ExitServiceMode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FP300Service
 * Method:    ClearDailyMemory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_ClearDailyMemory
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    FactorySettings
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_FactorySettings
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    CloseFM
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_CloseFM
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    SetExternalDevAddress
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetExternalDevAddress
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     FP300Service
 * Method:    UpdateFirmware
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_UpdateFirmware
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     FP300Service
 * Method:    PrintLogs
 * Signature: (LDateTime;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintLogs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     FP300Service
 * Method:    CreateDB
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_CreateDB
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    Connect
 * Signature: (LDeviceInfo;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_FP300Service_Connect
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     FP300Service
 * Method:    CheckPrinterStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_CheckPrinterStatus
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    GetLastResponse
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetLastResponse
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    CashIn
 * Signature: (D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_CashIn
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     FP300Service
 * Method:    CashOut
 * Signature: (D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_CashOut
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     FP300Service
 * Method:    CloseNFReceipt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_CloseNFReceipt
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    Fiscalize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_Fiscalize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FP300Service
 * Method:    StartFMTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_StartFMTest
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    GetDrawerInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetDrawerInfo
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    GetLastDocumentInfo
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetLastDocumentInfo
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     FP300Service
 * Method:    GetServiceCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetServiceCode
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    InterruptReport
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_InterruptReport
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    OpenDrawer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_OpenDrawer
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    SaveNetworkSettings
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SaveNetworkSettings
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     FP300Service
 * Method:    SetEJLimit
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_SetEJLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    StartEJ
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_StartEJ
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    StartFM
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_StartFM
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    StartNFReceipt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_StartNFReceipt
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    StartNFDocument
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_StartNFDocument
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    TransferFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_TransferFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FP300Service
 * Method:    WriteNFLine
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_WriteNFLine
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     FP300Service
 * Method:    GetPrinterDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetPrinterDate
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    PrintEJReport
 * Signature: (IIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintEJReport
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     FP300Service
 * Method:    GetLastLog
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetLastLog
  (JNIEnv *, jobject);

/*
 * Class:     FP300Service
 * Method:    PrintSystemInfoReport
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintSystemInfoReport
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    PrintReceiptTotalReport
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_PrintReceiptTotalReport
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    VoidPayment
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_VoidPayment
  (JNIEnv *, jobject, jint);

/*
 * Class:     FP300Service
 * Method:    GetEFTAuthorisation
 * Signature: (DILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FP300Service_GetEFTAuthorisation
  (JNIEnv *, jobject, jdouble, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
